# Generated by Django 5.2.3 on 2025-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_owner_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="working_hours",
            field=models.CharField(max_length=100, verbose_name="Время работы"),
        ),
    ]
